### ISSUE TITLE
content invisible on mobile screens

### ISSUE THREAD

**Issue by Dieterbe** [jaden/twentyfourteen#1]
Hey,
i'm using this theme (actually i slightly modified version),
and it looks like for sufficiently small screens, the content doesn't properly render.
see for example this screenshot from ios (looks the same on my android phone)
i'm not good at CSS but i'll try to find out what's wrong.
![slack_for_ios_upload_1024](https://cloud.githubusercontent.com/assets/20774/7544317/d9e00624-f599-11e4-94b9-0ed340fece0a.png)

**Comment by jaden** [comment]
Thanks for filing this. If you aren't able to figure it out, let me know and I'll see what I can find.

**Comment by Dieterbe** [comment]
i'm really bad at css and not much luck yet, but what i found out is that if the screen is <= about 400px, then the sidebar covers the screen and content is invisible.

**Comment by Dieterbe** [comment]
wow there really is a lot that can be found on this topic.
lots of people complaining about the bar not behaving properly, about hard-to-tweak css, there's a few CSS patches that can be applied (setting display to none in the media query for 400 max-width), and so on, i tried them all, but couldn't get it to work :(

**Comment by nikhilm** [comment]
I'm having the same problem, would love it if someone with more CSS chops could figure something out.

**Comment by jaden** [comment]
Thanks for the reminder. I just took a look at the issue and fixed it.

**Comment by nikhilm** [comment]
Thanks @jaden that worked.

**Comment by jaden** [comment]
Great! Thanks for confirming.
