### ISSUE TITLE
double slash

### ISSUE THREAD

**Issue by emicklei** [jaden/twentyfourteen#3]
I am using Hugo Static Site Generator v0.15-DEV BuildDate: 2015-11-18T21:07:40+01:00 with this theme and noticed that some urls are generated with an unexpected `//`  .

For example, in the recentpost.html `.Permalink` writes an ending slash such that the complete URL has suffix `//index.html`. 

Before I change all the templates, I want to check that I did not miss some config option.

Thank you for creating this theme

**Comment by jaden** [comment]
Thanks for letting me know. I'll take a look at this when I get a chance.

**Comment by jaden** [comment]
This happens if you have a trailing slash in baseurl. If you remove the trailing slash, you should only have single slashes.
